### ISSUE TITLE
Vendure types are outdated

### ISSUE THREAD

**Issue by macabeus** [vendure-ecommerce/deity-falcon-vendure-api#7]
I need to do some updates on this codebase, so I cloned this repository and I did `yarn link` on the server project created using `npx create-falcon-app`.

Before of `yarn link` everything was working fine, but after that I have some erros. Looks like that there are some outdated definitions on resolvers. On page setup it tries to get the categories, but can't understand what it is:
```
[2020-09-24 12:17:11.440] ERROR: Category was defined in resolvers, but it's not an object

GraphQL Error Code: INTERNAL_SERVER_ERROR
    Error: Category was defined in resolvers, but it's not an object
    undefined
```

And since it can't load the categories, the page can't be opened.

Just running the generate types we have a lot of updates on `vendure-types` files:

![image](https://user-images.githubusercontent.com/9501115/94139440-8a12eb80-fe61-11ea-8f75-8f1c41f57c05.png)

**Comment by michaelbromley** [comment]
Yes, this repo has not been updated for a while, that's true. Version 0.8.0 according to the readme. We're now on 0.15.1, so there are for sure a bunch of breaking changes in the mean time.

It's not currently my priority to update this repo, but I'll happily accept PRs if you wish to try to update it yourself.

**Comment by michaelbromley** [comment]
I'm closing this and archiving this repo because Deity just announced that Falcon will no longer be open source. In Slack messages dated 4th Nov 2020, it was announced:

> Falcon Open Source will no longer be available openly, but only in private repositories. 
> Q: will the npm packages still be openly available?
> they won't be openly available but if you need access we can give it to you and your team.

Therefore it is no longer feasible to maintain an adapter for what is now a closed-source project, where setting up a dev environment is not easy.
